import type { Product } from "./types";
import { placeholderImages } from './placeholder-images.json';

const products: Product[] = [
  {
    id: "pixel-8-pro",
    name: "Pixel 8 Pro",
    brand: "Google",
    storage: "256GB",
    price: 999,
    rating: 4.8,
    reviewCount: 1250,
    description: "The most powerful Pixel yet, with a pro-level camera system, a stunning display, and the new Google Tensor G3 chip. Experience AI-powered features that make your life easier.",
    specifications: {
      Display: "6.7-inch Super Actua LTPO OLED",
      Processor: "Google Tensor G3",
      RAM: "12GB",
      "Main Camera": "50MP Octa-PD wide",
      "Front Camera": "10.5MP Dual PD",
      Battery: "5,050 mAh",
    },
    images: placeholderImages.filter(img => img.id.startsWith("pixel-8-pro")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  },
  {
    id: "galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    storage: "512GB",
    price: 1299,
    rating: 4.9,
    reviewCount: 2340,
    description: "Unleash new levels of creativity and productivity with the Galaxy S24 Ultra. Featuring a revolutionary camera, the powerful Snapdragon 8 Gen 3 for Galaxy, and a built-in S Pen.",
    specifications: {
      Display: "6.8-inch Dynamic AMOLED 2X",
      Processor: "Snapdragon 8 Gen 3 for Galaxy",
      RAM: "12GB",
      "Main Camera": "200MP Wide-angle",
      "Front Camera": "12MP",
      Battery: "5,000 mAh",
    },
    images: placeholderImages.filter(img => img.id.startsWith("galaxy-s24-ultra")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    storage: "256GB",
    price: 1099,
    rating: 4.8,
    reviewCount: 3100,
    description: "Forged in titanium, the iPhone 15 Pro features the A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.",
    specifications: {
      Display: "6.1-inch Super Retina XDR",
      Processor: "A17 Pro Chip",
      RAM: "8GB",
      "Main Camera": "48MP Main",
      "Front Camera": "12MP TrueDepth",
      Battery: "Up to 23 hours video playback",
    },
    images: placeholderImages.filter(img => img.id.startsWith("iphone-15-pro")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    storage: "256GB",
    price: 799,
    rating: 4.7,
    reviewCount: 890,
    description: "The OnePlus 12 is a flagship masterpiece, offering a seamless experience with its elite performance, stunning display, and 4th Gen Hasselblad Camera for Mobile.",
    specifications: {
      Display: "6.82-inch 2K 120Hz ProXDR",
      Processor: "Snapdragon 8 Gen 3",
      RAM: "16GB",
      "Main Camera": "50MP Sony LYT-808",
      "Front Camera": "32MP",
      Battery: "5,400 mAh with 80W SUPERVOOC",
    },
    images: placeholderImages.filter(img => img.id.startsWith("oneplus-12")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  },
  {
    id: "xperia-1-v",
    name: "Xperia 1 V",
    brand: "Sony",
    storage: "256GB",
    price: 1399,
    rating: 4.6,
    reviewCount: 450,
    description: "Co-developed with the engineers behind the latest Alpha cameras, the Xperia 1 V offers an unprecedented imaging experience, a 4K HDR OLED display, and exceptional performance for creators.",
    specifications: {
      Display: "6.5-inch 4K HDR OLED 120Hz",
      Processor: "Snapdragon 8 Gen 2",
      RAM: "12GB",
      "Main Camera": "48MP Exmor T for mobile",
      "Front Camera": "12MP",
      Battery: "5,000 mAh",
    },
    images: placeholderImages.filter(img => img.id.startsWith("xperia-1-v")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  },
  {
    id: "pixel-7a",
    name: "Pixel 7a",
    brand: "Google",
    storage: "128GB",
    price: 499,
    rating: 4.7,
    reviewCount: 1800,
    description: "The Google Pixel 7a offers the best of Google's smarts in a more affordable package. Enjoy a fantastic camera, great performance with the Tensor G2 chip, and all-day battery life.",
    specifications: {
      Display: "6.1-inch FHD+ OLED",
      Processor: "Google Tensor G2",
      RAM: "8GB",
      "Main Camera": "64MP Quad Bayer wide",
      "Front Camera": "13MP",
      Battery: "4,385 mAh",
    },
    images: placeholderImages.filter(img => img.id.startsWith("pixel-7a")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  },
  {
    id: "galaxy-a54",
    name: "Galaxy A54 5G",
    brand: "Samsung",
    storage: "128GB",
    price: 449,
    rating: 4.5,
    reviewCount: 2150,
    description: "Awesome is for everyone. The Galaxy A54 5G combines a premium design, a versatile camera system, and a vibrant display to bring you an incredible mobile experience at a great value.",
    specifications: {
      Display: "6.4-inch Super AMOLED 120Hz",
      Processor: "Exynos 1380",
      RAM: "8GB",
      "Main Camera": "50MP OIS",
      "Front Camera": "32MP",
      Battery: "5,000 mAh",
    },
    images: placeholderImages.filter(img => img.id.startsWith("galaxy-a54")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  },
  {
    id: "iphone-se",
    name: "iPhone SE",
    brand: "Apple",
    storage: "128GB",
    price: 429,
    rating: 4.6,
    reviewCount: 2900,
    description: "The iPhone SE packs the powerful A15 Bionic chip into our most popular size. It's everything you love, for less than you expect.",
    specifications: {
      Display: "4.7-inch Retina HD",
      Processor: "A15 Bionic Chip",
      RAM: "4GB",
      "Main Camera": "12MP Wide",
      "Front Camera": "7MP FaceTime HD",
      Battery: "Up to 15 hours video playback",
    },
    images: placeholderImages.filter(img => img.id.startsWith("iphone-se")).map(img => ({ id: img.id, url: img.imageUrl, alt: img.description, hint: img.imageHint })),
  }
];

export function getProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}
