
import type { Product } from "./types";
import { placeholderImages } from './placeholder-images.json';

const allImages = placeholderImages.map(img => ({
  id: img.id,
  url: img.imageUrl,
  alt: img.description,
  hint: img.imageHint,
}));

export const products: Product[] = [
  {
    id: "pixel-8-pro",
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    model: 'Pixel 8 Pro',
    price: 999,
    storage: '128GB',
    color: 'Obsidian',
    stock: 50,
    rating: 4.8,
    reviewCount: 125,
    description: 'The Google Pixel 8 Pro is the most advanced Pixel phone yet, with a pro-level camera system, a powerful Google Tensor G3 chip, and a stunning 6.7-inch Super Actua display.',
    specifications: {
      Display: '6.7" Super Actua LTPO OLED',
      Chip: 'Google Tensor G3',
      RAM: '12GB',
      'Main Camera': '50MP Octa PD wide',
    },
    images: allImages.filter(img => img.id.startsWith('pixel-8-pro')),
  },
  {
    id: "galaxy-s24-ultra",
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    price: 1299,
    storage: '256GB',
    color: 'Titanium Gray',
    stock: 30,
    rating: 4.9,
    reviewCount: 210,
    description: 'Experience the new era of mobile AI with Galaxy S24 Ultra. It comes with a built-in S Pen, a pro-grade camera, and a powerful Snapdragon 8 Gen 3 for Galaxy chip.',
    specifications: {
      Display: '6.8" Dynamic AMOLED 2X',
      Chip: 'Snapdragon 8 Gen 3 for Galaxy',
      RAM: '12GB',
      'Main Camera': '200MP Wide-angle',
    },
    images: allImages.filter(img => img.id.startsWith('galaxy-s24-ultra')),
  },
  {
    id: "iphone-15-pro",
    name: 'Apple iPhone 15 Pro',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    price: 999,
    storage: '128GB',
    color: 'Natural Titanium',
    stock: 60,
    rating: 4.7,
    reviewCount: 350,
    description: 'Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
    specifications: {
      Display: '6.1" Super Retina XDR',
      Chip: 'A17 Pro',
      RAM: '8GB',
      'Main Camera': '48MP Main',
    },
    images: allImages.filter(img => img.id.startsWith('iphone-15-pro')),
  },
  {
    id: "oneplus-12",
    name: 'OnePlus 12',
    brand: 'OnePlus',
    model: '12',
    price: 799,
    storage: '256GB',
    color: 'Flowy Emerald',
    stock: 45,
    rating: 4.6,
    reviewCount: 95,
    description: 'The OnePlus 12 is a true flagship, featuring a stunning 2K 120Hz ProXDR display, the latest Snapdragon 8 Gen 3, and 4th Gen Hasselblad Camera for Mobile.',
    specifications: {
      Display: '6.82" 2K 120Hz ProXDR',
      Chip: 'Snapdragon 8 Gen 3',
      RAM: '16GB',
      'Main Camera': '50MP Sony\'s LYT-808',
    },
    images: allImages.filter(img => img.id.startsWith('oneplus-12')),
  },
  {
    id: "xperia-1-v",
    name: 'Sony Xperia 1 V',
    brand: 'Sony',
    model: 'Xperia 1 V',
    price: 1399,
    storage: '256GB',
    color: 'Khaki Green',
    stock: 20,
    rating: 4.5,
    reviewCount: 50,
    description: 'Next-gen sensor and computational processing for stunning low-light pictures, plus unique features for creators. Co-developed with the engineers behind the latest Alpha cameras.',
    specifications: {
      Display: '6.5" 4K HDR OLED',
      Chip: 'Snapdragon 8 Gen 2',
      RAM: '12GB',
      'Main Camera': '48MP Exmor T for mobile',
    },
    images: allImages.filter(img => img.id.startsWith('xperia-1-v')),
  },
  {
    id: "pixel-7a",
    name: 'Google Pixel 7a',
    brand: 'Google',
    model: 'Pixel 7a',
    price: 499,
    storage: '128GB',
    color: 'Charcoal',
    stock: 100,
    rating: 4.7,
    reviewCount: 180,
    description: 'The Google Pixel 7a is fast and efficient, with 8 GB of RAM, an amazing camera, and features that are rated highest in security.',
    specifications: {
      Display: '6.1" FHD+ OLED',
      Chip: 'Google Tensor G2',
      RAM: '8GB',
      'Main Camera': '64MP Quad PD Quad Bayer',
    },
    images: allImages.filter(img => img.id.startsWith('pixel-7a')),
  },
  {
    id: "galaxy-a54",
    name: 'Samsung Galaxy A54 5G',
    brand: 'Samsung',
    model: 'Galaxy A54 5G',
    price: 449,
    storage: '128GB',
    color: 'Awesome Violet',
    stock: 150,
    rating: 4.4,
    reviewCount: 250,
    description: 'Capture awesome videos with VDIS and a wider OIS angle. The premium glass finish, clean camera layout, and energizing colorways give the Galaxy A54 5G its Awesome identity.',
    specifications: {
      Display: '6.4" FHD+ Super AMOLED',
      Chip: 'Exynos 1380',
      RAM: '6GB',
      'Main Camera': '50MP OIS',
    },
    images: allImages.filter(img => img.id.startsWith('galaxy-a54')),
  },
  {
    id: "iphone-se",
    name: 'Apple iPhone SE (3rd generation)',
    brand: 'Apple',
    model: 'iPhone SE (3rd gen)',
    price: 429,
    storage: '128GB',
    color: 'Midnight',
    stock: 80,
    rating: 4.3,
    reviewCount: 300,
    description: 'Serious power with the A15 Bionic chip and a superstar camera. Plus, the toughest glass in a smartphone and a Home button with secure Touch ID.',
    specifications: {
      Display: '4.7" Retina HD',
      Chip: 'A15 Bionic',
      RAM: '4GB',
      'Main Camera': '12MP Wide',
    },
    images: allImages.filter(img => img.id.startsWith('iphone-se')),
  },
];

export function getProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}
