export type Product = {
  id: string;
  brand: string;
  model: string;
  capacity: '128GB' | '256GB' | '512GB' | '1TB';
  color: string;
  costPrice: number;
  salePrice: number;
  stock: number;
  description?: string;
  imageUrl?: string | null;
  lastUpdate: string;
  imei?: string;
  uniquePrice?: boolean;
  payInBill?: boolean;
  originalPrice?: number;
  discount?: number;
  installments?: number;
  installmentPrice?: number;
  taxedPrice?: number;
  shipping?: boolean;
};